import {
  LayoutDashboard, Sun, CalendarRange, CalendarDays, Calendar, Target, Sparkles,
  UtensilsCrossed, HeartHandshake, Sparkle, BookHeart, Lightbulb, CalendarCheck,
  Timer, Settings as SettingsIcon, BookOpen, HeartPulse, Wallet, Home,
  ShoppingBasket, Compass, Leaf, Flower2, Inbox, FolderOpen, NotebookPen, BadgeCheck, Repeat,
  Wind, PenLine, Coffee, Share2,
  Zap, Plane, Users, PartyPopper, Gift, CheckSquare, Heart, Album,
} from "lucide-react";

/** Per-flow accent classes for tints and gradients. */
export const FLOW_ACCENTS: Record<
  string,
  { text: string; bg: string; ring: string; border: string; gradient: string }
> = {
  planflow:   { text: "text-indigo-500",  bg: "bg-indigo-500/15",  ring: "ring-indigo-500/40",  border: "border-indigo-500/40",  gradient: "from-indigo-500/25 via-indigo-500/5 to-transparent" },
  careflow:   { text: "text-rose-500",    bg: "bg-rose-500/15",    ring: "ring-rose-500/40",    border: "border-rose-500/40",    gradient: "from-rose-500/25 via-rose-500/5 to-transparent" },
  homeflow:   { text: "text-amber-500",   bg: "bg-amber-500/15",   ring: "ring-amber-500/40",   border: "border-amber-500/40",   gradient: "from-amber-500/25 via-amber-500/5 to-transparent" },
  wellflow:   { text: "text-emerald-500", bg: "bg-emerald-500/15", ring: "ring-emerald-500/40", border: "border-emerald-500/40", gradient: "from-emerald-500/25 via-emerald-500/5 to-transparent" },
  growthflow: { text: "text-sky-500",     bg: "bg-sky-500/15",     ring: "ring-sky-500/40",     border: "border-sky-500/40",     gradient: "from-sky-500/25 via-sky-500/5 to-transparent" },
  moneyflow:  { text: "text-lime-600",    bg: "bg-lime-500/15",    ring: "ring-lime-500/40",    border: "border-lime-500/40",    gradient: "from-lime-500/25 via-lime-500/5 to-transparent" },
  lunarflow:  { text: "text-violet-500",  bg: "bg-violet-500/15",  ring: "ring-violet-500/40",  border: "border-violet-500/40",  gradient: "from-violet-500/25 via-violet-500/5 to-transparent" },
  seasonsflow:{ text: "text-pink-500",    bg: "bg-pink-500/15",    ring: "ring-pink-500/40",    border: "border-pink-500/40",    gradient: "from-pink-500/25 via-pink-500/5 to-transparent" },
  settings:   { text: "text-muted-foreground", bg: "bg-muted",     ring: "ring-border",         border: "border-border",         gradient: "from-muted/40 via-muted/10 to-transparent" },
};

/** Short descriptions for nav items, used on flow landing cards. */
export const NAV_DESCRIPTIONS: Record<string, string> = {
  "/inbox": "Capture anything fast and triage it later.",
  "/today": "Today's focus, brief, and time blocks.",
  "/plan": "Plan your day on a single timeline.",
  "/week": "Zoom out to a weekly rhythm.",
  "/month": "See the whole month at a glance.",
  "/year": "Map seasons, milestones, and themes.",
  "/calendar": "Unified calendar across sources.",
  "/upcoming": "What's coming up next.",
  "/anytime": "Tasks with no fixed date.",
  "/someday": "Ideas to revisit when the time is right.",
  "/not-today": "Snoozed out of today's view.",
  "/logbook": "Everything you've completed.",
  "/projects": "Multi-step work, organized.",
  "/focus": "Pomodoro and deep-work timers.",
  "/automations": "Automatic actions across the app.",
  "/review": "Past reviews and reflections.",
  "/care": "The CARE loop for caregivers.",
  "/caregiving": "Care plans, contacts, and check-ins.",
  "/family": "Household, members, and sharing.",
  "/mental-load": "Track invisible work and balance it.",
  "/home-areas": "Rooms, zones, and home life.",
  "/home-reset": "Resets, routines, and the home hub.",
  "/meals": "This week's meal plan.",
  "/meals/library": "Saved recipes and ideas.",
  "/pantry": "Inventory and shopping lists.",
  "/routines": "Repeatable rhythms for daily life.",
  "/trips": "Plan trips and packing lists.",
  "/health": "Health, energy, and check-ins.",
  "/habits": "Daily habits and streaks.",
  "/journal": "A quiet space to write.",
  "/journal-flow": "Guided journaling and flow.",
  "/goals": "Goals, milestones, and progress.",
  "/ideas": "Idea capture and incubation.",
  "/notes": "Notes, docs, and references.",
  "/whiteboards": "Free-form visual thinking.",
  "/graph": "Knowledge graph across notes.",
  "/tags": "Browse and manage tags.",
  "/wealth": "Budgets, accounts, and financial wellness.",
  "/rhythm": "Lunar and seasonal rhythms.",
  "/insights": "Patterns and reflections.",
  "/reset/week": "Close the week and prep the next.",
  "/reset/month": "Close the month and reset.",
  "/memories": "Moments worth remembering — your family memory book.",
  "/seasons": "Seasons, celebrations, and family rhythms.",
  "/seasons/celebrations": "Birthdays, anniversaries, and milestones.",
  "/seasons/holidays": "Holiday plans and prep timelines.",
  "/seasons/traditions": "Reusable family traditions.",
  "/seasons/bucket-lists": "Seasonal bucket lists.",
  "/seasons/remembrance": "Quiet space to remember loved ones.",
  "/cosmic-flow": "Astrology-aware planning: moon, transits, journal prompts.",
  "/cosmic-flow/timeline": "Upcoming cosmic events.",
  "/cosmic-flow/birth-chart": "Personalize Cosmic Flow with your birth info.",
  "/": "Your home dashboard.",
  "/settings": "Preferences, account, and integrations.",
};

export const NAV = [
  { to: "/", label: "Dashboard", icon: LayoutDashboard },
  { to: "/care", label: "CARE Loop", icon: Flower2 },
  { to: "/inbox", label: "Inbox", icon: Inbox },
  { to: "/projects", label: "Projects", icon: FolderOpen },
  { to: "/today", label: "Today", icon: Sun },
  { to: "/week", label: "Week", icon: CalendarRange },
  { to: "/month", label: "Month", icon: CalendarDays },
  { to: "/year", label: "Year", icon: Calendar },
  { to: "/goals", label: "Goals", icon: Target },
  { to: "/habits", label: "Habits", icon: Sparkles },
  { to: "/meals", label: "Meals", icon: UtensilsCrossed },
  { to: "/meals/library", label: "Meals Library", icon: BookOpen },
  { to: "/pantry", label: "Inventory", icon: ShoppingBasket },
  { to: "/caregiving", label: "Caregiving", icon: HeartHandshake },
  { to: "/trips", label: "Trips", icon: Plane },
  { to: "/routines", label: "Routines", icon: Repeat },
  { to: "/health", label: "Health", icon: HeartPulse },
  { to: "/wealth", label: "Wealth", icon: Wallet },
  { to: "/mental-load", label: "Mental Load", icon: Leaf },
  { to: "/home-areas", label: "Home", icon: Home },
  { to: "/home-reset", label: "Home Hub", icon: Sparkle },
  { to: "/journal", label: "Journal", icon: BookHeart },
  { to: "/journal-flow", label: "Journal & Flow", icon: Wind },
  { to: "/memories", label: "Memories", icon: Flower2 },
  { to: "/ideas", label: "Ideas", icon: Lightbulb },
  { to: "/calendar", label: "Calendar", icon: CalendarCheck },
  { to: "/seasons", label: "Seasons & Celebrations", icon: PartyPopper },
  { to: "/focus", label: "Focus", icon: Timer },
  { to: "/settings", label: "Settings", icon: SettingsIcon },
] as const;

export const MOBILE_NAV = [
  { to: "/inbox", label: "Inbox", icon: Inbox },
  { to: "/today", label: "Today", icon: Sun },
  { to: "/calendar", label: "Calendar", icon: CalendarCheck },
  { to: "/home-areas", label: "Home", icon: Home },
  { to: "/meals", label: "Meals", icon: UtensilsCrossed },
  { to: "/notes", label: "Notes", icon: NotebookPen },
] as const;

/** Grouped navigation for the categorized sidebar. */
export const NAV_GROUPS = [
  {
    id: "planflow",
    label: "PlanFlow",
    subtitle: "Planning & Productivity",
    emoji: "📅",
    icon: CalendarDays,
    items: [
      { to: "/inbox", label: "Inbox", icon: Inbox },
      { to: "/today", label: "Today", icon: Sun },
      { to: "/plan", label: "Daily Plan", icon: Sparkles },
      { to: "/week", label: "Week", icon: CalendarRange },
      { to: "/month", label: "Month", icon: CalendarDays },
      { to: "/year", label: "Year", icon: Calendar },
      { to: "/calendar", label: "Calendar", icon: CalendarCheck },
      { to: "/upcoming", label: "Upcoming", icon: CalendarRange },
      { to: "/anytime", label: "Anytime", icon: Sparkles },
      { to: "/someday", label: "Someday", icon: Lightbulb },
      { to: "/not-today", label: "Not Today", icon: Coffee },
      { to: "/logbook", label: "Logbook", icon: BookOpen },
      { to: "/projects", label: "Projects", icon: FolderOpen },
      { to: "/focus", label: "Focus", icon: Timer },
      { to: "/automations", label: "Automations", icon: Zap },
      { to: "/review", label: "Reviews Timeline", icon: BadgeCheck },
    ],
  },
  {
    id: "careflow",
    label: "CareFlow",
    subtitle: "Family & Caregiving",
    emoji: "💚",
    icon: HeartHandshake,
    items: [
      { to: "/care", label: "CARE Loop", icon: Flower2 },
      { to: "/caregiving", label: "Caregiving", icon: HeartHandshake },
      { to: "/family", label: "Family & sharing", icon: Users },
      { to: "/mental-load", label: "Mental Load", icon: Leaf },
    ],
  },
  {
    id: "homeflow",
    label: "HomeFlow",
    subtitle: "Home Management",
    emoji: "🏠",
    icon: Home,
    items: [
      { to: "/home-areas", label: "Home", icon: Home },
      { to: "/home-reset", label: "Home Hub", icon: Sparkle },
      { to: "/meals", label: "Meals", icon: UtensilsCrossed },
      { to: "/meals/library", label: "Meals Library", icon: BookOpen },
      { to: "/pantry", label: "Inventory", icon: ShoppingBasket },
      { to: "/routines", label: "Routines", icon: Repeat },
      { to: "/trips", label: "Trips", icon: Plane },
    ],
  },
  {
    id: "wellflow",
    label: "WellFlow",
    subtitle: "Wellness & Self-Care",
    emoji: "🌿",
    icon: Leaf,
    items: [
      { to: "/health", label: "Health", icon: HeartPulse },
      { to: "/habits", label: "Habits", icon: Sparkles },
      { to: "/journal", label: "Journal", icon: BookHeart },
      { to: "/journal-flow", label: "Journal & Flow", icon: Wind },
    ],
  },
  {
    id: "growthflow",
    label: "GrowthFlow",
    subtitle: "Learning & Goals",
    emoji: "📚",
    icon: Target,
    items: [
      { to: "/goals", label: "Goals", icon: Target },
      { to: "/ideas", label: "Ideas", icon: Lightbulb },
      { to: "/notes", label: "Notes", icon: NotebookPen },
      { to: "/whiteboards", label: "Whiteboards", icon: PenLine },
      { to: "/graph", label: "Knowledge Graph", icon: Share2 },
      { to: "/tags", label: "Tags", icon: BadgeCheck },
    ],
  },
  {
    id: "moneyflow",
    label: "MoneyFlow",
    subtitle: "Budgeting & Financial Wellness",
    emoji: "💰",
    icon: Wallet,
    items: [
      { to: "/wealth", label: "Wealth", icon: Wallet },
    ],
  },
  {
    id: "lunarflow",
    label: "LunarFlow",
    subtitle: "Reflection & Intentional Living",
    emoji: "🌙",
    icon: Flower2,
    items: [
      { to: "/rhythm", label: "Rhythm", icon: Flower2 },
      { to: "/insights", label: "Insights", icon: Sparkles },
      { to: "/reset/week", label: "Weekly Reset", icon: CalendarRange },
      { to: "/reset/month", label: "Monthly Reset", icon: CalendarDays },
      { to: "/memories", label: "Memories", icon: Flower2 },
    ],
  },
  {
    id: "seasonsflow",
    label: "Seasons & Celebrations",
    subtitle: "Plan, celebrate, remember",
    emoji: "✨",
    icon: PartyPopper,
    items: [
      { to: "/seasons", label: "Dashboard", icon: LayoutDashboard },
      { to: "/seasons/celebrations", label: "Celebrations", icon: PartyPopper },
      { to: "/seasons/holidays", label: "Holidays", icon: Gift },
      { to: "/seasons/traditions", label: "Traditions", icon: Repeat },
      { to: "/memories", label: "Memory Book", icon: Album },
      { to: "/seasons/bucket-lists", label: "Bucket Lists", icon: CheckSquare },
      { to: "/seasons/remembrance", label: "Remembrance", icon: Heart },
    ],
  },
  {
    id: "settings",
    label: "Settings",
    subtitle: "Preferences & Automations",
    emoji: "⚙️",
    icon: SettingsIcon,
    items: [
      { to: "/", label: "Dashboard", icon: LayoutDashboard },
      { to: "/settings", label: "Settings", icon: SettingsIcon },
    ],
  },
] as const;
