import {
  LayoutDashboard, Sun, CalendarRange, CalendarDays, Calendar, Target, Sparkles,
  UtensilsCrossed, HeartHandshake, Sparkle, BookHeart, Lightbulb, CalendarCheck,
  Timer, Settings as SettingsIcon, BookOpen, HeartPulse, Wallet, Home,
  ShoppingBasket, Compass, Leaf, Flower2, Inbox, FolderOpen, NotebookPen, BadgeCheck, Repeat,
  Wind, PenLine, Coffee, Share2,
  Zap, Plane, Users,
} from "lucide-react";

export const NAV = [
  { to: "/", label: "Dashboard", icon: LayoutDashboard },
  { to: "/care", label: "CARE Loop", icon: Flower2 },
  { to: "/inbox", label: "Inbox", icon: Inbox },
  { to: "/projects", label: "Projects", icon: FolderOpen },
  { to: "/today", label: "Today", icon: Sun },
  { to: "/week", label: "Week", icon: CalendarRange },
  { to: "/month", label: "Month", icon: CalendarDays },
  { to: "/year", label: "Year", icon: Calendar },
  { to: "/goals", label: "Goals", icon: Target },
  { to: "/habits", label: "Habits", icon: Sparkles },
  { to: "/meals", label: "Meals", icon: UtensilsCrossed },
  { to: "/meals/library", label: "Meals Library", icon: BookOpen },
  { to: "/pantry", label: "Inventory", icon: ShoppingBasket },
  { to: "/caregiving", label: "Caregiving", icon: HeartHandshake },
  { to: "/trips", label: "Trips", icon: Plane },
  { to: "/routines", label: "Routines", icon: Repeat },
  { to: "/health", label: "Health", icon: HeartPulse },
  { to: "/wealth", label: "Wealth", icon: Wallet },
  { to: "/mental-load", label: "Mental Load", icon: Leaf },
  { to: "/home-areas", label: "Home", icon: Home },
  { to: "/home-reset", label: "Home Hub", icon: Sparkle },
  { to: "/journal", label: "Journal", icon: BookHeart },
  { to: "/journal-flow", label: "Journal & Flow", icon: Wind },
  { to: "/memories", label: "Memories", icon: Flower2 },
  { to: "/ideas", label: "Ideas", icon: Lightbulb },
  { to: "/calendar", label: "Calendar", icon: CalendarCheck },
  { to: "/focus", label: "Focus", icon: Timer },
  { to: "/settings", label: "Settings", icon: SettingsIcon },
] as const;

export const MOBILE_NAV = [
  { to: "/inbox", label: "Inbox", icon: Inbox },
  { to: "/today", label: "Today", icon: Sun },
  { to: "/calendar", label: "Calendar", icon: CalendarCheck },
  { to: "/home-areas", label: "Home", icon: Home },
  { to: "/meals", label: "Meals", icon: UtensilsCrossed },
  { to: "/notes", label: "Notes", icon: NotebookPen },
] as const;

/** Grouped navigation for the categorized sidebar. */
export const NAV_GROUPS = [
  {
    id: "planflow",
    label: "PlanFlow",
    subtitle: "Planning & Productivity",
    emoji: "📅",
    icon: CalendarDays,
    items: [
      { to: "/inbox", label: "Inbox", icon: Inbox },
      { to: "/today", label: "Today", icon: Sun },
      { to: "/plan", label: "Daily Plan", icon: Sparkles },
      { to: "/week", label: "Week", icon: CalendarRange },
      { to: "/month", label: "Month", icon: CalendarDays },
      { to: "/year", label: "Year", icon: Calendar },
      { to: "/calendar", label: "Calendar", icon: CalendarCheck },
      { to: "/upcoming", label: "Upcoming", icon: CalendarRange },
      { to: "/anytime", label: "Anytime", icon: Sparkles },
      { to: "/someday", label: "Someday", icon: Lightbulb },
      { to: "/not-today", label: "Not Today", icon: Coffee },
      { to: "/logbook", label: "Logbook", icon: BookOpen },
      { to: "/projects", label: "Projects", icon: FolderOpen },
      { to: "/focus", label: "Focus", icon: Timer },
      { to: "/automations", label: "Automations", icon: Zap },
      { to: "/review", label: "Reviews Timeline", icon: BadgeCheck },
    ],
  },
  {
    id: "careflow",
    label: "CareFlow",
    subtitle: "Family & Caregiving",
    emoji: "💚",
    icon: HeartHandshake,
    items: [
      { to: "/care", label: "CARE Loop", icon: Flower2 },
      { to: "/caregiving", label: "Caregiving", icon: HeartHandshake },
      { to: "/family", label: "Family & sharing", icon: Users },
      { to: "/mental-load", label: "Mental Load", icon: Leaf },
    ],
  },
  {
    id: "homeflow",
    label: "HomeFlow",
    subtitle: "Home Management",
    emoji: "🏠",
    icon: Home,
    items: [
      { to: "/home-areas", label: "Home", icon: Home },
      { to: "/home-reset", label: "Home Hub", icon: Sparkle },
      { to: "/meals", label: "Meals", icon: UtensilsCrossed },
      { to: "/meals/library", label: "Meals Library", icon: BookOpen },
      { to: "/pantry", label: "Inventory", icon: ShoppingBasket },
      { to: "/routines", label: "Routines", icon: Repeat },
      { to: "/trips", label: "Trips", icon: Plane },
    ],
  },
  {
    id: "wellflow",
    label: "WellFlow",
    subtitle: "Wellness & Self-Care",
    emoji: "🌿",
    icon: Leaf,
    items: [
      { to: "/health", label: "Health", icon: HeartPulse },
      { to: "/habits", label: "Habits", icon: Sparkles },
      { to: "/journal", label: "Journal", icon: BookHeart },
      { to: "/journal-flow", label: "Journal & Flow", icon: Wind },
    ],
  },
  {
    id: "growthflow",
    label: "GrowthFlow",
    subtitle: "Learning & Goals",
    emoji: "📚",
    icon: Target,
    items: [
      { to: "/goals", label: "Goals", icon: Target },
      { to: "/ideas", label: "Ideas", icon: Lightbulb },
      { to: "/notes", label: "Notes", icon: NotebookPen },
      { to: "/whiteboards", label: "Whiteboards", icon: PenLine },
      { to: "/graph", label: "Knowledge Graph", icon: Share2 },
      { to: "/tags", label: "Tags", icon: BadgeCheck },
    ],
  },
  {
    id: "moneyflow",
    label: "MoneyFlow",
    subtitle: "Budgeting & Financial Wellness",
    emoji: "💰",
    icon: Wallet,
    items: [
      { to: "/wealth", label: "Wealth", icon: Wallet },
    ],
  },
  {
    id: "lunarflow",
    label: "LunarFlow",
    subtitle: "Reflection & Intentional Living",
    emoji: "🌙",
    icon: Flower2,
    items: [
      { to: "/rhythm", label: "Rhythm", icon: Flower2 },
      { to: "/insights", label: "Insights", icon: Sparkles },
      { to: "/reset/week", label: "Weekly Reset", icon: CalendarRange },
      { to: "/reset/month", label: "Monthly Reset", icon: CalendarDays },
      { to: "/memories", label: "Memories", icon: Flower2 },
    ],
  },
  {
    id: "settings",
    label: "Settings",
    subtitle: "Preferences & Automations",
    emoji: "⚙️",
    icon: SettingsIcon,
    items: [
      { to: "/", label: "Dashboard", icon: LayoutDashboard },
      { to: "/settings", label: "Settings", icon: SettingsIcon },
    ],
  },
] as const;
