import type { RitualTemplate } from "./RitualSession";

export const RITUAL_TEMPLATES: RitualTemplate[] = [
  {
    id: "morning-activation",
    name: "Morning Activation",
    intent: "energize",
    intensity: "moderate",
    description: "Wake the body up with breath, mobility, and a gentle pulse.",
    emoji: "🌅",
    color: "hsl(20 75% 62%)",
    steps: [
      { title: "Deep breaths", seconds: 60, cue: "Inhale 4 · exhale 6, nose only" },
      { title: "Cat-cow flow", seconds: 90, cue: "Move with your breath" },
      { title: "Sun salutation A", seconds: 180, cue: "3 rounds, slow" },
      { title: "Standing twists", seconds: 60, cue: "Hands on hips, rotate" },
      { title: "Jumping jacks", seconds: 60, cue: "Or step-touch if low energy" },
      { title: "Stillness", seconds: 60, cue: "Notice how you feel now" },
    ],
  },
  {
    id: "desk-reset",
    name: "Desk Reset",
    intent: "soften",
    intensity: "light",
    description: "A 5-minute unwind for tight shoulders and screen eyes.",
    emoji: "💻",
    color: "hsl(145 45% 50%)",
    steps: [
      { title: "Shoulder rolls", seconds: 45, cue: "Slow, both directions" },
      { title: "Neck stretches", seconds: 60, cue: "Ear to shoulder, hold" },
      { title: "Chest opener", seconds: 60, cue: "Hands clasped behind back" },
      { title: "Forward fold", seconds: 60, cue: "Soft knees, let head hang" },
      { title: "Eye reset", seconds: 30, cue: "Look 20 ft away" },
    ],
  },
  {
    id: "evening-restore",
    name: "Evening Restore",
    intent: "restore",
    intensity: "light",
    description: "Slow yin shapes to release the day before sleep.",
    emoji: "🌙",
    color: "hsl(220 50% 60%)",
    steps: [
      { title: "Child's pose", seconds: 120, cue: "Knees wide, soft arms" },
      { title: "Sphinx", seconds: 90, cue: "Open the front body" },
      { title: "Reclined twist (R)", seconds: 90, cue: "Surrender to gravity" },
      { title: "Reclined twist (L)", seconds: 90, cue: "Match the other side" },
      { title: "Legs up the wall", seconds: 180, cue: "Long, slow breaths" },
      { title: "Savasana", seconds: 120, cue: "Let everything settle" },
    ],
  },
  {
    id: "box-breath",
    name: "Box Breath Reset",
    intent: "breathe",
    intensity: "light",
    description: "Calm the nervous system in 4 minutes — anywhere.",
    emoji: "🫁",
    color: "hsl(180 40% 55%)",
    steps: [
      { title: "Settle in", seconds: 30, cue: "Find a tall, easy seat" },
      { title: "Round 1", seconds: 64, cue: "In 4 · hold 4 · out 4 · hold 4 (×4)" },
      { title: "Round 2", seconds: 64, cue: "Same pattern, eyes soft" },
      { title: "Round 3", seconds: 64, cue: "Last round, savor it" },
      { title: "Notice", seconds: 30, cue: "Scan the body for change" },
    ],
  },
  {
    id: "grounding-walk",
    name: "Grounding Walk",
    intent: "ground",
    intensity: "light",
    description: "A 15-minute mindful walk to come back into the body.",
    emoji: "🌳",
    color: "hsl(30 35% 50%)",
    steps: [
      { title: "Set an intention", seconds: 60, cue: "One word for this walk" },
      { title: "Slow steps", seconds: 180, cue: "Feel each foot connect" },
      { title: "Sense check", seconds: 60, cue: "5 things you can see" },
      { title: "Natural pace", seconds: 360, cue: "Let the body lead" },
      { title: "Slow steps", seconds: 180, cue: "Wind back down" },
      { title: "Pause", seconds: 60, cue: "Notice the air on your skin" },
    ],
  },
  {
    id: "dance-break",
    name: "Dance Break",
    intent: "play",
    intensity: "moderate",
    description: "Three songs of unsupervised movement. No rules.",
    emoji: "💃",
    color: "hsl(340 65% 65%)",
    steps: [
      { title: "Shake it out", seconds: 60, cue: "Hands, shoulders, hips" },
      { title: "Song 1", seconds: 180, cue: "Whatever feels good" },
      { title: "Song 2", seconds: 180, cue: "Go bigger if you can" },
      { title: "Song 3", seconds: 180, cue: "Slow it down or push" },
      { title: "Pause", seconds: 30, cue: "Feel the aliveness" },
    ],
  },
  {
    id: "strength-flow",
    name: "Strength Flow",
    intent: "energize",
    intensity: "vigorous",
    description: "Body-weight circuit to build heat and capacity.",
    emoji: "💪",
    color: "hsl(0 65% 60%)",
    steps: [
      { title: "Warm-up march", seconds: 90, cue: "High knees, swing arms" },
      { title: "Squats", seconds: 60, cue: "Slow down, fast up" },
      { title: "Push-ups", seconds: 45, cue: "Knees down if needed" },
      { title: "Rest", seconds: 30 },
      { title: "Lunges", seconds: 60, cue: "Alternate sides" },
      { title: "Glute bridges", seconds: 45, cue: "Squeeze at the top" },
      { title: "Rest", seconds: 30 },
      { title: "Plank", seconds: 45, cue: "Long spine, breathe" },
      { title: "Cool down stretch", seconds: 120, cue: "Hamstrings, hips, chest" },
    ],
  },
  {
    id: "low-energy-honor",
    name: "Low Energy Honor",
    intent: "soften",
    intensity: "light",
    description: "When your body says rest but you still want to move.",
    emoji: "🕯️",
    color: "hsl(265 45% 65%)",
    steps: [
      { title: "Lie down", seconds: 60, cue: "Knees bent, palms up" },
      { title: "Belly breathing", seconds: 120, cue: "Let the belly rise" },
      { title: "Knee hugs", seconds: 90, cue: "One side, then the other" },
      { title: "Supported butterfly", seconds: 180, cue: "Pillows under knees" },
      { title: "Self-massage", seconds: 120, cue: "Hands, jaw, scalp" },
      { title: "Rest", seconds: 120, cue: "You did enough" },
    ],
  },
];