export const PACKING_TEMPLATES: Record<string, Array<{ name: string; category: string; quantity?: number }>> = {
  Beach: [
    { name: "Swimsuit", category: "Clothing", quantity: 2 },
    { name: "Sunscreen", category: "Toiletries" },
    { name: "Sunglasses", category: "Clothing" },
    { name: "Beach towel", category: "Other" },
    { name: "Flip flops", category: "Clothing" },
    { name: "Hat", category: "Clothing" },
    { name: "Light shirts", category: "Clothing", quantity: 5 },
    { name: "Shorts", category: "Clothing", quantity: 3 },
    { name: "Phone charger", category: "Electronics" },
    { name: "Passport / ID", category: "Documents" },
  ],
  City: [
    { name: "Comfortable shoes", category: "Clothing" },
    { name: "Day bag", category: "Other" },
    { name: "Reusable water bottle", category: "Other" },
    { name: "Jacket", category: "Clothing" },
    { name: "Outfits", category: "Clothing", quantity: 5 },
    { name: "Toothbrush", category: "Toiletries" },
    { name: "Phone charger", category: "Electronics" },
    { name: "Portable battery", category: "Electronics" },
    { name: "Passport / ID", category: "Documents" },
    { name: "Travel adapter", category: "Electronics" },
  ],
  Business: [
    { name: "Suit / formal outfit", category: "Clothing" },
    { name: "Dress shoes", category: "Clothing" },
    { name: "Laptop + charger", category: "Electronics" },
    { name: "Notebook + pen", category: "Other" },
    { name: "Business cards", category: "Documents" },
    { name: "Toiletry kit", category: "Toiletries" },
    { name: "Travel adapter", category: "Electronics" },
    { name: "Passport / ID", category: "Documents" },
  ],
  Camping: [
    { name: "Tent", category: "Other" },
    { name: "Sleeping bag", category: "Other" },
    { name: "Headlamp", category: "Electronics" },
    { name: "Bug spray", category: "Toiletries" },
    { name: "First aid kit", category: "Other" },
    { name: "Hiking boots", category: "Clothing" },
    { name: "Rain jacket", category: "Clothing" },
    { name: "Water filter", category: "Other" },
    { name: "Snacks", category: "Other" },
    { name: "Multi-tool", category: "Other" },
  ],
};